services:
  cloudnas:
    image: cloudnas/clouddrive2
    container_name: clouddrive2
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    volumes:
      - ./CloudNAS:/CloudNAS:shared
      - ./Config:/Config
      # - ./media:shared     # 可选项服务器本地硬盘存储映射，可以挂载到网络作为云盘使用，请自行将需要的硬盘或目录进行挂载
    devices:
      - /dev/fuse:/dev/fuse
    restart: unless-stopped
    pid: "host"
    privileged: true
    network_mode: "host"
    ports:
      - 19798:19798   # 用于kejilion脚本应用模板替换
